version: '3'
services:
  test:
    image: asecurityteam/sdcli:v1
    environment:
      # config values for integration tests
      DYNAMO_ENDPOINT: http://localstack:4569
      DYNAMO_REGION: us-east-1
      S3_ENDPOINT: http://localstack:4572
      S3_REGION: us-east-1
      # required for aws sdk
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    command: go integration
    working_dir: ${PROJECT_PATH}
    volumes:
      - ${DIR}:${PROJECT_PATH}
    depends_on:
      - localstack
  localstack:
    image: localstack/localstack:0.10.2
    environment:
      - LOCALSTACK_SERVICES=dynamodb,s3
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
